# Generated by Django 5.0.6 on 2024-07-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hair_color_changer_app', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
